# Generated by Django 5.2.7 on 2025-11-02 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssemblyMachine1Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_code_internal", models.CharField(max_length=100)),
                ("qr_code_external", models.CharField(max_length=100)),
                ("qr_code_housing", models.CharField(max_length=100)),
                ("status", models.CharField(default="OK", max_length=10)),
            ],
            options={
                "db_table": "assembly_machine_1_postprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AssemblyMachine1Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "machine_name",
                    models.CharField(default="Assembly Machine 1", max_length=50),
                ),
                ("qr_code_internal", models.CharField(max_length=100)),
                (
                    "previous_piston_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "assembly_machine_1_preprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AssemblyMachine2Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_code_internal", models.CharField(max_length=100)),
                ("qr_code_external", models.CharField(max_length=100)),
                ("qr_code_housing", models.CharField(max_length=100)),
                ("status", models.CharField(default="OK", max_length=10)),
            ],
            options={
                "db_table": "assembly_machine_2_postprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AssemblyMachine2Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "machine_name",
                    models.CharField(default="Assembly Machine 2", max_length=50),
                ),
                ("qr_code_internal", models.CharField(max_length=100)),
                (
                    "previous_piston_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "assembly_machine_2_preprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AssemblyMachine3Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_code_internal", models.CharField(max_length=100)),
                ("qr_code_external", models.CharField(max_length=100)),
                ("qr_code_housing", models.CharField(max_length=100)),
                ("status", models.CharField(default="OK", max_length=10)),
            ],
            options={
                "db_table": "assembly_machine_3_postprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AssemblyMachine3Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "machine_name",
                    models.CharField(default="Assembly Machine 3", max_length=50),
                ),
                ("qr_code_internal", models.CharField(max_length=100)),
                (
                    "previous_piston_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "assembly_machine_3_preprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AssemblyMachine4Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_code_internal", models.CharField(max_length=100)),
                ("qr_code_external", models.CharField(max_length=100)),
                ("qr_code_housing", models.CharField(max_length=100)),
                ("status", models.CharField(default="OK", max_length=10)),
            ],
            options={
                "db_table": "assembly_machine_4_postprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AssemblyMachine4Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "machine_name",
                    models.CharField(default="Assembly Machine 4", max_length=50),
                ),
                ("qr_code_internal", models.CharField(max_length=100)),
                (
                    "previous_piston_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "assembly_machine_4_preprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DeburringPostprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "deburring_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="DeburringPreprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_honing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "deburring_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori1Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "dmg_mori_1_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori1Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "dmg_mori_1_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori2Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "dmg_mori_2_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori2Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "dmg_mori_2_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori3Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "dmg_mori_3_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori3Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "dmg_mori_3_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori4Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "dmg_mori_4_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori4Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "dmg_mori_4_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori5Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "dmg_mori_5_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori5Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "dmg_mori_5_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori6Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "dmg_mori_6_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="DmgMori6Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "dmg_mori_6_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="FinalWashingPostprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "final_washing_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="FinalWashingPreprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_prewashing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "final_washing_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="Gauge1Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
                ("value1", models.FloatField(blank=True, null=True)),
                ("value2", models.FloatField(blank=True, null=True)),
                ("value3", models.FloatField(blank=True, null=True)),
                ("value4", models.FloatField(blank=True, null=True)),
                ("value5", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "gauge_1_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="Gauge1Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_machine_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "gauge_1_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="Gauge2Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
                ("value1", models.FloatField(blank=True, null=True)),
                ("value2", models.FloatField(blank=True, null=True)),
                ("value3", models.FloatField(blank=True, null=True)),
                ("value4", models.FloatField(blank=True, null=True)),
                ("value5", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "gauge_2_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="Gauge2Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_machine_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "gauge_2_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="Gauge3Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
                ("value1", models.FloatField(blank=True, null=True)),
                ("value2", models.FloatField(blank=True, null=True)),
                ("value3", models.FloatField(blank=True, null=True)),
                ("value4", models.FloatField(blank=True, null=True)),
                ("value5", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "gauge_3_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="Gauge3Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_machine_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "gauge_3_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="Honing1Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "honing_1_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="Honing1Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_gauge_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "honing_1_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="Honing2Postprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "honing_2_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="Honing2Preprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_gauge_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "honing_2_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="LubricationPostprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_code", models.CharField(max_length=100)),
                ("status", models.CharField(default="OK", max_length=10)),
            ],
            options={
                "db_table": "lubrication_postprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="LubricationPreprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_painting_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("qr_code", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "lubrication_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="MasterTraceability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qr_code", models.CharField(max_length=100, unique=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[("PISTON", "Piston"), ("HOUSING", "Housing")],
                        max_length=20,
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("IN_PROCESS", "In Process"),
                            ("OK", "OK"),
                            ("NG", "NG"),
                            ("SCRAPPED", "Scrapped"),
                            ("COMPLETE", "Complete"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_machine",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "start_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_update_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "dmg_mori_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "dmg_mori_machine",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("dmg_mori_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "gauge_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "gauge_machine",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("gauge_timestamp", models.DateTimeField(blank=True, null=True)),
                ("gauge_value1", models.FloatField(blank=True, null=True)),
                ("gauge_value2", models.FloatField(blank=True, null=True)),
                ("gauge_value3", models.FloatField(blank=True, null=True)),
                ("gauge_value4", models.FloatField(blank=True, null=True)),
                ("gauge_value5", models.FloatField(blank=True, null=True)),
                (
                    "honing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "honing_machine",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("honing_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "deburring_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("deburring_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "prewashing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("prewashing_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "final_washing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "final_washing_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "assembly_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "assembly_machine",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("assembly_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "assembly_internal_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assembly_external_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "assembly_housing_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "leak_test_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("leak_test_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "painting_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("painting_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "lubrication_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("lubrication_timestamp", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "renata_traceability",
                "ordering": ["-last_update_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OringLeakTestPostprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_code", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "oring_leak_test_postprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="OringLeakTestPreprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_assembly_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("qr_code", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "oring_leak_test_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="PaintingPostprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_code", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "painting_postprocessing",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="PaintingPreprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_leak_test_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("qr_code", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "painting_preprocessing",
            },
        ),
        migrations.CreateModel(
            name="PrewashingPostprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "prewashing_postprocessing",
            },
        ),
        migrations.CreateModel(
            name="PrewashingPreprocessing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                (
                    "previous_deburring_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
            ],
            options={
                "db_table": "prewashing_preprocessing",
            },
        ),
    ]
