# Generated by Django 5.2.7 on 2025-12-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cnc1Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "cnc1_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc1Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "cnc1_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc2Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "cnc2_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc2Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "cnc2_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc3Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "cnc3_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc3Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "cnc3_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc4Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "cnc4_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc4Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "cnc4_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc5Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "cnc5_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc5Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "cnc5_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc6Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "cnc6_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Cnc6Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("machine_name", models.CharField(max_length=50)),
                ("qr_data", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "cnc6_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DeburringPostprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "deburring_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="DeburringPreprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "deburring_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FinalwashingPostprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "finalwashing_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="FinalwashingPreprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "finalwashing_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Gauge1Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
                ("value1", models.FloatField(blank=True, null=True)),
                ("value2", models.FloatField(blank=True, null=True)),
                ("value3", models.FloatField(blank=True, null=True)),
                ("value4", models.FloatField(blank=True, null=True)),
                ("value5", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "gauge1_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Gauge1Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "gauge1_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Gauge2Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
                ("value1", models.FloatField(blank=True, null=True)),
                ("value2", models.FloatField(blank=True, null=True)),
                ("value3", models.FloatField(blank=True, null=True)),
                ("value4", models.FloatField(blank=True, null=True)),
                ("value5", models.FloatField(blank=True, null=True)),
                ("value6", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "gauge2_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Gauge2Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "gauge2_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Gauge3Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
                ("value1", models.FloatField(blank=True, null=True)),
                ("value2", models.FloatField(blank=True, null=True)),
                ("value3", models.FloatField(blank=True, null=True)),
                ("value4", models.FloatField(blank=True, null=True)),
                ("value5", models.FloatField(blank=True, null=True)),
                ("value6", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "gauge3_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Gauge3Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "gauge3_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Honing1Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "honing1_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Honing1Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "honing1_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Honing2Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "honing2_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Honing2Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "honing2_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LubPostprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data_piston", models.CharField(max_length=100, unique=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "lub_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="LubPreprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data_piston", models.CharField(max_length=100, unique=True)),
                (
                    "model_name_piston",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "qr_data_housing",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "model_name_housing",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("previous_machine_status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "lub_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Op40AProcessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp_internal", models.DateTimeField()),
                ("qr_data_internal", models.CharField(max_length=100, unique=True)),
                ("previous_machine_internal_status", models.CharField(max_length=10)),
                ("model_name_internal", models.CharField(max_length=20)),
                ("timestamp_external", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_data_external",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_external",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("timestamp_housing", models.DateTimeField(blank=True, null=True)),
                (
                    "previous_machine_housing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "qr_data_housing",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_housing",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "op40a_processing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Op40BProcessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp_internal", models.DateTimeField()),
                ("qr_data_internal", models.CharField(max_length=100, unique=True)),
                ("previous_machine_internal_status", models.CharField(max_length=10)),
                ("model_name_internal", models.CharField(max_length=20)),
                ("timestamp_external", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_data_external",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_external",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("timestamp_housing", models.DateTimeField(blank=True, null=True)),
                (
                    "previous_machine_housing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "qr_data_housing",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_housing",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "op40b_processing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Op40CProcessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp_internal", models.DateTimeField()),
                ("qr_data_internal", models.CharField(max_length=100, unique=True)),
                ("previous_machine_internal_status", models.CharField(max_length=10)),
                ("model_name_internal", models.CharField(max_length=20)),
                ("timestamp_external", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_data_external",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_external",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("timestamp_housing", models.DateTimeField(blank=True, null=True)),
                (
                    "previous_machine_housing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "qr_data_housing",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_housing",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "op40c_processing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Op40DProcessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp_internal", models.DateTimeField()),
                ("qr_data_internal", models.CharField(max_length=100, unique=True)),
                ("previous_machine_internal_status", models.CharField(max_length=10)),
                ("model_name_internal", models.CharField(max_length=20)),
                ("timestamp_external", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_data_external",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_external",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("timestamp_housing", models.DateTimeField(blank=True, null=True)),
                (
                    "previous_machine_housing_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "qr_data_housing",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_housing",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "op40d_processing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Op80Postprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data_housing_new", models.CharField(max_length=100, unique=True)),
                (
                    "qr_data_housing",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("match_status", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "op80_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Op80Preprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data_piston", models.CharField(max_length=100, unique=True)),
                ("model_name_internal", models.CharField(max_length=20)),
                (
                    "qr_data_housing",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_external",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("previous_machine_status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "op80_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PaintingPostprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(blank=True, max_length=100, null=True)),
                ("qr_data_piston", models.CharField(max_length=100, unique=True)),
                (
                    "qr_data_housing",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "painting_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PaintingPreprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                (
                    "qr_data_housing",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_housing",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "qr_data_piston",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "model_name_piston",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("pre_status", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "painting_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PrewashingPostprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "prewashing_postprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PrewashingPreprocessing",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("timestamp", models.CharField(max_length=100)),
                ("qr_data", models.CharField(max_length=100)),
                ("previous_machine_status", models.CharField(max_length=10)),
                ("status", models.CharField(max_length=10)),
                ("model_name", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "prewashing_preprocessing",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
    ]
